export const SAGA_GET_SHOPS = 'SAGA_GET_SHOPS';
export const SAGA_GET_SHOPS_SUCCESS = 'SAGA_GET_SHOPS_SUCCESS';
export const SAGA_GET_SHOPS_FAIL = 'SAGA_GET_SHOPS_FAIL';

export const SAGA_GET_GOODS = 'SAGA_GET_GOODS';
export const SAGA_GET_GOODS_SUCCESS = 'SAGA_GET_GOODS_SUCCESS';
export const SAGA_GET_GOODS_FAIL = 'SAGA_GET_GOODS_FAIL';

export const SAGA_CREATE_ORDER = 'SAGA_CREATE_ORDER';
export const SAGA_CREATE_ORDER_SUCCESS = 'SAGA_CREATE_ORDER_SUCCESS';
export const SAGA_CREATE_ORDER_FAIL = 'SAGA_CREATE_ORDER_FAIL';

export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER';
export const SAGA_REGISTER_USER_SUCCESS = 'SAGA_REGISTER_USER_SUCCESS';
export const SAGA_REGISTER_USER_FAIL = 'SAGA_REGISTER_USER_FAIL';

export const SAGA_LOGIN_USER = 'SAGA_LOGIN_USER';
export const SAGA_LOGIN_USER_SUCCESS = 'SAGA_LOGIN_USER_SUCCESS';
export const SAGA_LOGIN_USER_FAIL = 'SAGA_LOGIN_USER_FAIL';

export const SET_CURRENT_SHOP = 'SET_CURRENT_SHOP';
export const SET_CURRENT_SHOP_SUCCESS = 'SET_CURRENT_SHOP_SUCCESS';
export const SET_CURRENT_SHOP_FAIL = 'SET_CURRENT_SHOP_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS';
export const REMOVE_ITEM_FROM_CART_FAIL = 'REMOVE_ITEM_FROM_CART_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const RESET_CART = 'RESET_CART';
export const RESET_CART_SUCCESS = 'RESET_CART_SUCCESS';
export const RESET_CART_FAIL = 'RESET_CART_FAIL';

// Admin panel

export const SAGA_ADD_SHOP = 'SAGA_ADD_SHOP';
export const SAGA_ADD_SHOP_SUCCESS = 'SAGA_ADD_SHOP_SUCCESS';
export const SAGA_ADD_SHOP_FAIL = 'SAGA_ADD_SHOP_FAIL';

export const SAGA_ADD_GOOD = 'SAGA_ADD_GOOD';
export const SAGA_ADD_GOOD_SUCCESS = 'SAGA_ADD_GOOD_SUCCESS';
export const SAGA_ADD_GOOD_FAIL = 'SAGA_ADD_GOOD_FAIL';

export const SAGA_REMOVE_PRODUCT = 'SAGA_REMOVE_PRODUCT';
export const SAGA_REMOVE_PRODUCT_SUCCESS = 'SAGA_REMOVE_PRODUCT_SUCCESS';
export const SAGA_REMOVE_PRODUCT_FAIL = 'SAGA_REMOVE_PRODUCT_FAIL';